AllCops:
  Exclude:
    - tmp/**/*

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 15

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceAroundOperators:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*_spec.rb

Style/AndOr:
  EnforcedStyle: conditionals
